### ISSUE TITLE
Consider Acknowledging Use of neat-python Code in Your Project

### ISSUE THREAD

**Issue by WLS2002** [SamanKhamesian/Hybrid-Self-Attention-NEAT#3]
Hey there,

I was taking a look at your code in the "neat" package and couldn't help but notice that it's really similar to the stuff in the neat-python GitHub repo (https://github.com/CodeReclaimers/neat-python). But I couldn't find any mention of neat-python in your paper or on the GitHub page for your project.

I totally get that neat-python is under the 3-clause BSD license and anyone can use the code however they like. But it's usually a good move to give a shout-out to the code you've used, especially when it's a big chunk.

Just a suggestion - maybe consider mentioning that you've used some code from neat-python somewhere in your project page or future papers if it indeed was a big help in your work. It could clear up where the code came from and it's a nice nod to the authors of neat-python.

Thanks for considering, and keep up the good work!

Best,
wls2002

**Comment by SamanKhamesian** [comment]
Hi there,

I hope this email finds you well.

I want to express my gratitude for reaching out and raising the issue
regarding the "neat package."
Your diligence and attention to detail are greatly appreciated.

I fully agree with you and recognize the significance of the matter you've
raised.
I would like to mention that I have already listed the packages I used in
the Abstract section of the GitHub repository, which contains the
PurePython library: https://github.com/ukuleleplayer/pureples.
However, I understand the importance of addressing your project's specific
implementation of the neat algorithm as well.

The "neat package" has been an invaluable resource throughout our
development process.
Its robust features and functionality have significantly contributed to the
success of our project thus far.

Once again, I would like to extend my respect and gratitude to you for
bringing this issue to my attention.
Your dedication to quality and your contributions to our project are truly
valued.
Please rest assured that I will work diligently to address this matter and
mention your project in the GitHub repository.

If you have any further insights or suggestions regarding this issue or any
other aspect of the project, please feel free to share them.
I am always open to feedback and collaboration.

Thank you once again for your dedication and for being an integral part of
our project's success.

Best regards,
Saman Khamesian
